import fdb
from .config import settings


_pool = None


def get_connection():
    return fdb.connect(
        dsn=settings.FIREBIRD_DSN,
        user=settings.FIREBIRD_USER,
        password=settings.FIREBIRD_PASSWORD,
        charset="UTF8",
    )


def table_exists(conn, table_name):
    cur = conn.cursor()
    cur.execute(
        "SELECT COUNT(*) FROM RDB$RELATIONS WHERE RDB$RELATION_NAME = ?",
        (table_name.upper(),),
    )
    count = cur.fetchone()[0]
    cur.close()
    return count > 0


def init_db():
    conn = get_connection()
    cur = conn.cursor()

    if not table_exists(conn, "PETS"):
        cur.execute("""
            CREATE TABLE pets (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(100) NOT NULL,
                breed VARCHAR(100),
                age VARCHAR(50),
                gender VARCHAR(20),
                height VARCHAR(20),
                weight VARCHAR(20),
                color VARCHAR(50),
                description BLOB SUB_TYPE TEXT,
                image_path VARCHAR(255),
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)

    if not table_exists(conn, "APPLICATIONS"):
        cur.execute("""
            CREATE TABLE applications (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                pet_id INTEGER,
                name VARCHAR(100) NOT NULL,
                email VARCHAR(150),
                phone VARCHAR(30),
                message BLOB SUB_TYPE TEXT,
                status VARCHAR(20) DEFAULT 'new',
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)

    if not table_exists(conn, "ADMINS"):
        cur.execute("""
            CREATE TABLE admins (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username VARCHAR(50) UNIQUE NOT NULL,
                password_hash VARCHAR(255) NOT NULL
            )
        """)

    conn.commit()
    cur.close()
    conn.close()


def seed_pets():
    conn = get_connection()
    cur = conn.cursor()

    cur.execute("SELECT COUNT(*) FROM pets")
    count = cur.fetchone()[0]
    if count > 0:
        cur.close()
        conn.close()
        return

    pets = [
        ("Бобик", "Лабрадор-ретривер", "2 года", "Мальчик", "56 см", "29 кг", "Палевый",
         "Бобик — ласковый и игривый лабрадор, который обожает детей и прогулки в парке. Он был найден на улице совсем щенком, но быстро стал настоящим другом для всех волонтёров приюта. Бобик отлично ладит с другими собаками и кошками, знает базовые команды и готов к переезду в любящую семью.",
         "images/pet_11.jpg"),
        ("Рекс", "Немецкая овчарка", "3 года", "Мальчик", "62 см", "34 кг", "Чёрно-бурый",
         "Рекс — верный друг и охранник. Знает базовые команды, очень предан хозяину. Был найден привязанным к столбу, но до сих пор верит в людей.",
         "images/pet_12.jpg"),
        ("Мушка", "Такса", "5 лет", "Девочка", "35 см", "9 кг", "Шоколадный",
         "Мушка — тихая и спокойная такса. Идеальна для пожилых людей или тех, кто ищет компаньона для тихих вечеров. Любит лежать на коленях и тихонько ворчать от удовольствия.",
         "images/pet_13.jpg"),
        ("Тузик", "Беспородный", "1 год", "Мальчик", "45 см", "18 кг", "Рыжий",
         "Тузик — энергичный и любопытный щенок. Обожает бегать и играть с мячом. Найден бродящим по дороге, но уже готов стать лучшим другом для активной семьи.",
         "images/pet_14.jpg"),
        ("Шарик", "Кавказская овчарка", "4 года", "Мальчик", "70 см", "52 кг", "Серый",
         "Шарик — весёлый и добрый пёс. Любит возиться на диване и смотреть в окно. Несмотря на внушительный размер, очень ласковый и спокойный.",
         "images/pet_15.jpg"),
        ("Дружок", "Бордер-колли", "2 года", "Мальчик", "50 см", "20 кг", "Чёрно-белый",
         "Дружок — умный и послушный пёс. Быстро учится новому, обожает фриби и головоломки. Идеален для тех, кто хочет активного и сообразительного компаньона.",
         "images/pet_16.jpg"),
    ]

    cur.executemany(
        "INSERT INTO pets (name, breed, age, gender, height, weight, color, description, image_path) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)",
        pets,
    )

    conn.commit()
    cur.close()
    conn.close()


def seed_admin():
    import bcrypt
    from .config import settings

    conn = get_connection()
    cur = conn.cursor()

    cur.execute("SELECT COUNT(*) FROM admins")
    count = cur.fetchone()[0]
    if count > 0:
        cur.close()
        conn.close()
        return

    password_hash = bcrypt.hashpw(
        settings.ADMIN_PASSWORD.encode(), bcrypt.gensalt()
    ).decode()

    cur.execute(
        "INSERT INTO admins (username, password_hash) VALUES (?, ?)",
        (settings.ADMIN_USERNAME, password_hash),
    )

    conn.commit()
    cur.close()
    conn.close()
